steps:
  # Step 1: Building the server side
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/educonnect",  "Dockerfile", "."]

  # Step 2: Pushing the server image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/educonnect"]

  # Step 3: Deploying to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "your-app"
      - "--image=gcr.io/$PROJECT_ID/educonnect"
      - "--region=asia-south1"
      - "--platform=managed"
      - "--set-env-vars=SECRET_NAME=$(gcloud secrets versions access latest --secret=educonnect-secret-keys)"
      - "--allow-unauthenticated"
options:
  logging: CLOUD_LOGGING_ONLY  # Setting logging option to CLOUD_LOGGING_ONLY
